[build]
    base = "client/"
    publish = "client/build/"
    command = "npm run build"

[[redirects]]
    from = "/*"
    to = "/"
    status = 200

[context.production]
    command = "npm run build"